{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 2}, "tests": {"0": {"status": "ERROR", "message": "@pytest.fixture()\n    def make_folders():\n>       return ssh_checkout(data[\"ip\"], data[\"user\"], data[\"passwd\"],\n                            f\"mkdir {data['folder_in']} {data['folder_out']} {data['folder_ext']} {data['folder_ext2']}\",\n                            \"\")\n\nconftest.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nssh_checkers.py:7: in ssh_checkout\n    client.connect(hostname=host, username=user, password=passwd, port=port)\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:485: in connect\n    self._auth(\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:818: in _auth\n    raise saved_exception\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:805: in _auth\n    self._transport.auth_password(username, password)\n../../.venv/lib/python3.10/site-packages/paramiko/transport.py:1603: in auth_password\n    return self.auth_handler.wait_for_response(my_event)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <paramiko.auth_handler.AuthHandler object at 0x73a346541270>, event = <threading.Event object at 0x73a346541180>\n\n    def wait_for_response(self, event):\n        max_ts = None\n        if self.transport.auth_timeout is not None:\n            max_ts = time.time() + self.transport.auth_timeout\n        while True:\n            event.wait(0.1)\n            if not self.transport.is_active():\n                e = self.transport.get_exception()\n                if (e is None) or issubclass(e.__class__, EOFError):\n                    e = AuthenticationException(\n                        \"Authentication failed: transport shut down or saw EOF\"\n                    )\n                raise e\n            if event.is_set():\n                break\n            if max_ts is not None and max_ts <= time.time():\n                raise AuthenticationException(\"Authentication timeout.\")\n    \n        if not self.is_authenticated():\n            e = self.transport.get_exception()\n            if e is None:\n                e = AuthenticationException(\"Authentication failed.\")\n            # this is horrible.  Python Exception isn't yet descended from\n            # object, so type(e) won't work. :(\n            # TODO 4.0: lol. just lmao.\n            if issubclass(e.__class__, PartialAuthentication):\n                return e.allowed_types\n>           raise e\nE           paramiko.ssh_exception.AuthenticationException: Authentication failed.\n\n../../.venv/lib/python3.10/site-packages/paramiko/auth_handler.py:263: AuthenticationException\n", "test_name": "test_nstep1", "rerun": "0"}, "1": {"status": "ERROR", "message": "@pytest.fixture()\n    def clear_folders():\n>       return ssh_checkout(\n            data[\"ip\"], data[\"user\"], data[\"passwd\"],\n            f\"rm -rf {data['folder_in']}/* {data['folder_out']}/* {data['folder_ext']}/* {data['folder_ext2']}/*\",\n            \"\")\n\nconftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nssh_checkers.py:7: in ssh_checkout\n    client.connect(hostname=host, username=user, password=passwd, port=port)\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:485: in connect\n    self._auth(\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:818: in _auth\n    raise saved_exception\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:805: in _auth\n    self._transport.auth_password(username, password)\n../../.venv/lib/python3.10/site-packages/paramiko/transport.py:1603: in auth_password\n    return self.auth_handler.wait_for_response(my_event)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <paramiko.auth_handler.AuthHandler object at 0x73a34541a500>, event = <threading.Event object at 0x73a34541a440>\n\n    def wait_for_response(self, event):\n        max_ts = None\n        if self.transport.auth_timeout is not None:\n            max_ts = time.time() + self.transport.auth_timeout\n        while True:\n            event.wait(0.1)\n            if not self.transport.is_active():\n                e = self.transport.get_exception()\n                if (e is None) or issubclass(e.__class__, EOFError):\n                    e = AuthenticationException(\n                        \"Authentication failed: transport shut down or saw EOF\"\n                    )\n                raise e\n            if event.is_set():\n                break\n            if max_ts is not None and max_ts <= time.time():\n                raise AuthenticationException(\"Authentication timeout.\")\n    \n        if not self.is_authenticated():\n            e = self.transport.get_exception()\n            if e is None:\n                e = AuthenticationException(\"Authentication failed.\")\n            # this is horrible.  Python Exception isn't yet descended from\n            # object, so type(e) won't work. :(\n            # TODO 4.0: lol. just lmao.\n            if issubclass(e.__class__, PartialAuthentication):\n                return e.allowed_types\n>           raise e\nE           paramiko.ssh_exception.AuthenticationException: Authentication failed.\n\n../../.venv/lib/python3.10/site-packages/paramiko/auth_handler.py:263: AuthenticationException\n", "test_name": "test_nstep2", "rerun": "0"}}, "suite_name": "test_negative.py"}, "1": {"suite_name": "test_positive.py", "tests": {"0": {"status": "ERROR", "message": "@pytest.fixture()\n    def make_folders():\n>       return ssh_checkout(data[\"ip\"], data[\"user\"], data[\"passwd\"],\n                            f\"mkdir {data['folder_in']} {data['folder_out']} {data['folder_ext']} {data['folder_ext2']}\",\n                            \"\")\n\nconftest.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nssh_checkers.py:7: in ssh_checkout\n    client.connect(hostname=host, username=user, password=passwd, port=port)\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:485: in connect\n    self._auth(\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:818: in _auth\n    raise saved_exception\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:805: in _auth\n    self._transport.auth_password(username, password)\n../../.venv/lib/python3.10/site-packages/paramiko/transport.py:1603: in auth_password\n    return self.auth_handler.wait_for_response(my_event)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <paramiko.auth_handler.AuthHandler object at 0x73a34653ae90>, event = <threading.Event object at 0x73a34653aa40>\n\n    def wait_for_response(self, event):\n        max_ts = None\n        if self.transport.auth_timeout is not None:\n            max_ts = time.time() + self.transport.auth_timeout\n        while True:\n            event.wait(0.1)\n            if not self.transport.is_active():\n                e = self.transport.get_exception()\n                if (e is None) or issubclass(e.__class__, EOFError):\n                    e = AuthenticationException(\n                        \"Authentication failed: transport shut down or saw EOF\"\n                    )\n                raise e\n            if event.is_set():\n                break\n            if max_ts is not None and max_ts <= time.time():\n                raise AuthenticationException(\"Authentication timeout.\")\n    \n        if not self.is_authenticated():\n            e = self.transport.get_exception()\n            if e is None:\n                e = AuthenticationException(\"Authentication failed.\")\n            # this is horrible.  Python Exception isn't yet descended from\n            # object, so type(e) won't work. :(\n            # TODO 4.0: lol. just lmao.\n            if issubclass(e.__class__, PartialAuthentication):\n                return e.allowed_types\n>           raise e\nE           paramiko.ssh_exception.AuthenticationException: Authentication failed.\n\n../../.venv/lib/python3.10/site-packages/paramiko/auth_handler.py:263: AuthenticationException\n", "test_name": "test_step1", "rerun": "0"}, "1": {"status": "ERROR", "message": "@pytest.fixture()\n    def clear_folders():\n>       return ssh_checkout(\n            data[\"ip\"], data[\"user\"], data[\"passwd\"],\n            f\"rm -rf {data['folder_in']}/* {data['folder_out']}/* {data['folder_ext']}/* {data['folder_ext2']}/*\",\n            \"\")\n\nconftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nssh_checkers.py:7: in ssh_checkout\n    client.connect(hostname=host, username=user, password=passwd, port=port)\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:485: in connect\n    self._auth(\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:818: in _auth\n    raise saved_exception\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:805: in _auth\n    self._transport.auth_password(username, password)\n../../.venv/lib/python3.10/site-packages/paramiko/transport.py:1603: in auth_password\n    return self.auth_handler.wait_for_response(my_event)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <paramiko.auth_handler.AuthHandler object at 0x73a345463be0>, event = <threading.Event object at 0x73a345461cc0>\n\n    def wait_for_response(self, event):\n        max_ts = None\n        if self.transport.auth_timeout is not None:\n            max_ts = time.time() + self.transport.auth_timeout\n        while True:\n            event.wait(0.1)\n            if not self.transport.is_active():\n                e = self.transport.get_exception()\n                if (e is None) or issubclass(e.__class__, EOFError):\n                    e = AuthenticationException(\n                        \"Authentication failed: transport shut down or saw EOF\"\n                    )\n                raise e\n            if event.is_set():\n                break\n            if max_ts is not None and max_ts <= time.time():\n                raise AuthenticationException(\"Authentication timeout.\")\n    \n        if not self.is_authenticated():\n            e = self.transport.get_exception()\n            if e is None:\n                e = AuthenticationException(\"Authentication failed.\")\n            # this is horrible.  Python Exception isn't yet descended from\n            # object, so type(e) won't work. :(\n            # TODO 4.0: lol. just lmao.\n            if issubclass(e.__class__, PartialAuthentication):\n                return e.allowed_types\n>           raise e\nE           paramiko.ssh_exception.AuthenticationException: Authentication failed.\n\n../../.venv/lib/python3.10/site-packages/paramiko/auth_handler.py:263: AuthenticationException\n", "test_name": "test_step2", "rerun": "0"}, "2": {"status": "FAIL", "message": "       paramiko.ssh_exception.AuthenticationException: Authentication failed.\n", "test_name": "test_step3", "rerun": "0"}, "3": {"status": "FAIL", "message": "       paramiko.ssh_exception.AuthenticationException: Authentication failed.\n", "test_name": "test_step4", "rerun": "0"}, "4": {"status": "ERROR", "message": "@pytest.fixture()\n    def clear_folders():\n>       return ssh_checkout(\n            data[\"ip\"], data[\"user\"], data[\"passwd\"],\n            f\"rm -rf {data['folder_in']}/* {data['folder_out']}/* {data['folder_ext']}/* {data['folder_ext2']}/*\",\n            \"\")\n\nconftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nssh_checkers.py:7: in ssh_checkout\n    client.connect(hostname=host, username=user, password=passwd, port=port)\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:485: in connect\n    self._auth(\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:818: in _auth\n    raise saved_exception\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:805: in _auth\n    self._transport.auth_password(username, password)\n../../.venv/lib/python3.10/site-packages/paramiko/transport.py:1603: in auth_password\n    return self.auth_handler.wait_for_response(my_event)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <paramiko.auth_handler.AuthHandler object at 0x73a3451c4d00>, event = <threading.Event object at 0x73a3451c48e0>\n\n    def wait_for_response(self, event):\n        max_ts = None\n        if self.transport.auth_timeout is not None:\n            max_ts = time.time() + self.transport.auth_timeout\n        while True:\n            event.wait(0.1)\n            if not self.transport.is_active():\n                e = self.transport.get_exception()\n                if (e is None) or issubclass(e.__class__, EOFError):\n                    e = AuthenticationException(\n                        \"Authentication failed: transport shut down or saw EOF\"\n                    )\n                raise e\n            if event.is_set():\n                break\n            if max_ts is not None and max_ts <= time.time():\n                raise AuthenticationException(\"Authentication timeout.\")\n    \n        if not self.is_authenticated():\n            e = self.transport.get_exception()\n            if e is None:\n                e = AuthenticationException(\"Authentication failed.\")\n            # this is horrible.  Python Exception isn't yet descended from\n            # object, so type(e) won't work. :(\n            # TODO 4.0: lol. just lmao.\n            if issubclass(e.__class__, PartialAuthentication):\n                return e.allowed_types\n>           raise e\nE           paramiko.ssh_exception.AuthenticationException: Authentication failed.\n\n../../.venv/lib/python3.10/site-packages/paramiko/auth_handler.py:263: AuthenticationException\n", "test_name": "test_step5", "rerun": "0"}, "5": {"status": "ERROR", "message": "self = <paramiko.Transport at 0x466f60b0 (unconnected)>\n\n    def _check_banner(self):\n        # this is slow, but we only have to do it once\n        for i in range(100):\n            # give them 15 seconds for the first line, then just 2 seconds\n            # each additional line.  (some sites have very high latency.)\n            if i == 0:\n                timeout = self.banner_timeout\n            else:\n                timeout = 2\n            try:\n>               buf = self.packetizer.readline(timeout)\n\n../../.venv/lib/python3.10/site-packages/paramiko/transport.py:2327: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../../.venv/lib/python3.10/site-packages/paramiko/packet.py:381: in readline\n    buf += self._read_timeout(timeout)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <paramiko.packet.Packetizer object at 0x73a3466f6410>, timeout = 2\n\n    def _read_timeout(self, timeout):\n        start = time.time()\n        while True:\n            try:\n                x = self.__socket.recv(128)\n                if len(x) == 0:\n>                   raise EOFError()\nE                   EOFError\n\n../../.venv/lib/python3.10/site-packages/paramiko/packet.py:618: EOFError\n\nDuring handling of the above exception, another exception occurred:\n\n    @pytest.fixture()\n    def clear_folders():\n>       return ssh_checkout(\n            data[\"ip\"], data[\"user\"], data[\"passwd\"],\n            f\"rm -rf {data['folder_in']}/* {data['folder_out']}/* {data['folder_ext']}/* {data['folder_ext2']}/*\",\n            \"\")\n\nconftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nssh_checkers.py:7: in ssh_checkout\n    client.connect(hostname=host, username=user, password=passwd, port=port)\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:451: in connect\n    t.start_client(timeout=timeout)\n../../.venv/lib/python3.10/site-packages/paramiko/transport.py:738: in start_client\n    raise e\n../../.venv/lib/python3.10/site-packages/paramiko/transport.py:2143: in run\n    self._check_banner()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <paramiko.Transport at 0x466f60b0 (unconnected)>\n\n    def _check_banner(self):\n        # this is slow, but we only have to do it once\n        for i in range(100):\n            # give them 15 seconds for the first line, then just 2 seconds\n            # each additional line.  (some sites have very high latency.)\n            if i == 0:\n                timeout = self.banner_timeout\n            else:\n                timeout = 2\n            try:\n                buf = self.packetizer.readline(timeout)\n            except ProxyCommandFailure:\n                raise\n            except Exception as e:\n>               raise SSHException(\n                    \"Error reading SSH protocol banner\" + str(e)\n                )\nE               paramiko.ssh_exception.SSHException: Error reading SSH protocol banner\n\n../../.venv/lib/python3.10/site-packages/paramiko/transport.py:2331: SSHException\n", "test_name": "test_step6", "rerun": "0"}, "6": {"status": "FAIL", "message": "       paramiko.ssh_exception.AuthenticationException: Authentication failed.\n", "test_name": "test_step7", "rerun": "0"}, "7": {"status": "ERROR", "message": "self = <paramiko.Transport at 0x45402830 (unconnected)>\n\n    def _check_banner(self):\n        # this is slow, but we only have to do it once\n        for i in range(100):\n            # give them 15 seconds for the first line, then just 2 seconds\n            # each additional line.  (some sites have very high latency.)\n            if i == 0:\n                timeout = self.banner_timeout\n            else:\n                timeout = 2\n            try:\n>               buf = self.packetizer.readline(timeout)\n\n../../.venv/lib/python3.10/site-packages/paramiko/transport.py:2327: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../../.venv/lib/python3.10/site-packages/paramiko/packet.py:381: in readline\n    buf += self._read_timeout(timeout)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <paramiko.packet.Packetizer object at 0x73a345400190>, timeout = 2\n\n    def _read_timeout(self, timeout):\n        start = time.time()\n        while True:\n            try:\n                x = self.__socket.recv(128)\n                if len(x) == 0:\n>                   raise EOFError()\nE                   EOFError\n\n../../.venv/lib/python3.10/site-packages/paramiko/packet.py:618: EOFError\n\nDuring handling of the above exception, another exception occurred:\n\n    @pytest.fixture()\n    def clear_folders():\n>       return ssh_checkout(\n            data[\"ip\"], data[\"user\"], data[\"passwd\"],\n            f\"rm -rf {data['folder_in']}/* {data['folder_out']}/* {data['folder_ext']}/* {data['folder_ext2']}/*\",\n            \"\")\n\nconftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nssh_checkers.py:7: in ssh_checkout\n    client.connect(hostname=host, username=user, password=passwd, port=port)\n../../.venv/lib/python3.10/site-packages/paramiko/client.py:451: in connect\n    t.start_client(timeout=timeout)\n../../.venv/lib/python3.10/site-packages/paramiko/transport.py:738: in start_client\n    raise e\n../../.venv/lib/python3.10/site-packages/paramiko/transport.py:2143: in run\n    self._check_banner()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <paramiko.Transport at 0x45402830 (unconnected)>\n\n    def _check_banner(self):\n        # this is slow, but we only have to do it once\n        for i in range(100):\n            # give them 15 seconds for the first line, then just 2 seconds\n            # each additional line.  (some sites have very high latency.)\n            if i == 0:\n                timeout = self.banner_timeout\n            else:\n                timeout = 2\n            try:\n                buf = self.packetizer.readline(timeout)\n            except ProxyCommandFailure:\n                raise\n            except Exception as e:\n>               raise SSHException(\n                    \"Error reading SSH protocol banner\" + str(e)\n                )\nE               paramiko.ssh_exception.SSHException: Error reading SSH protocol banner\n\n../../.venv/lib/python3.10/site-packages/paramiko/transport.py:2331: SSHException\n", "test_name": "test_step8", "rerun": "0"}}, "status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 3, "total_error": 5}}}}, "date": "June 02, 2024", "start_time": 1717358575.410776, "total_suite": 2, "status": "FAIL", "status_list": {"pass": "0", "fail": "3", "skip": "0", "error": "7", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "10"}